### ISSUE TITLE
Erro login

### ISSUE THREAD

**Issue by raisiqueira** [devtotvs/generator-totvs-dev#2]
estou tentando baixar o HTML framework, porém está dando erro, pedindo usuário. Já tentei meu usuário do Painel do cliente, porém sem sucesso!

**Comment by raisiqueira** [comment]
Como que faz para baixar o Totvs HTML framework, tendo em mente que a página solicita login. Já tentei com meu usuário do Fluig porém sem sucesso!

**Comment by jhosefmarks** [comment]
Conversa com o Fabio Moraes Rocha pra ver o seu acesso.

**Comment by raisiqueira** [comment]
@jhosefmarks como que consigo o contato dele?

**Comment by jhosefmarks** [comment]
@raisiqueira você é da Totvs?

**Comment by devtotvs** [comment]
O THF está liberado apenas para equipes da TOTVS por enquanto.
