### ISSUE TITLE
Nome do projeto com espaço

### ISSUE THREAD

**Issue by williamgueiros** [devtotvs/generator-totvs-dev#5]
Caso venha a utilizar o espaço como delimitador.

![captura de tela 2016-12-12 as 15 00 55](https://cloud.githubusercontent.com/assets/19972/21109352/cc437d68-c07f-11e6-8ba5-e7eaa1e07421.png)

Ao realizar a geração do mesmo encontramos a seguinte saída de dados.

![captura de tela 2016-12-12 as 15 00 37](https://cloud.githubusercontent.com/assets/19972/21109399/0d92eaec-c080-11e6-9ab4-bb4f6dd61dd4.png)

existem duas abordagens
1- Limitar os caracteres para apenas _-
2- Realizar a correção para aceitar qualquer caracter

Recomendo a 2, mas ainda não iniciei o processo de analise fonte para correção do mesmo.

Qual modo estaria de acordo ?

**Comment by jhosefmarks** [comment]
O nome do projeto é usado para "configurar" os arquivos package.json e o bower.json, eles não aceitam espaços, por isso existe um titulo do projeto para incluir no index.html.

**Comment by williamgueiros** [comment]
@jhosefmarks Concorda comigo que poderíamos validar isso?
para que não seja gerado transtorno, pois o dev que irá utilizar pode acabar passando direto sem olhar .

**Comment by fabiomr78** [comment]
Concordo em validar a existencia de espaço no nome

**Comment by williamgueiros** [comment]
@jhosefmarks concordo 

conhece este cara:
https://www.npmjs.com/package/sanitize-filename

Até minutos atrás eu não o conhecia, e algumas destas limitações de windows.

Outra coisa que podemos fazer e igual a microsoft faz no TFS podemos usar urlEncode para o nome de projeto, assim ele faria algo assim (teste teste = teste%20teste).

@fabiomr78 prefere a solução 1 
e eu a solução 2

Poderia desempatar isso para nós ?

**Comment by jhosefmarks** [comment]
Na verdade a gente resolve usando o módulo lodash que já está sendo usado no generator.

Existe a função kebabCase que resolve isso pra gente.

https://lodash.com/docs/4.17.2#kebabCase

Em breve atualizarei o generator com essa melhoria.

**Comment by williamgueiros** [comment]
Agora ficou assim ao Digitar testeTeste

![captura de tela 2016-12-19 as 14 52 43](https://cloud.githubusercontent.com/assets/19972/21321186/f1f70b6c-c5fa-11e6-8678-6bb8ce4a662e.png)

**Comment by jhosefmarks** [comment]
Testou com espaço entre os nomes???

Outra coisa, deixa o nome da variável referente ao módulo como lodash mesmo, fica mais fácil de ler para quem não estiver acostumado com o módulo.

**Comment by williamgueiros** [comment]
fiz 2 exemplos:
O primeiro inserindo (teste  teste) e o segundo (teste  Teste)

![screen shot 2016-12-20 at 10 34 04](https://cloud.githubusercontent.com/assets/19972/21350734/059300fe-c6a0-11e6-8a91-29d95028c2df.png)

Ele está deixando apenas um - para ambos os casos, mas como o mesmo está sendo informado ao usuário não vejo grandes problemas, outro modo seriamos validar mesmo e obrigar a inserir do modo correto, e mais questão de escolha não existe bala de prata.

Quanto a trocar do Lodash, realmente deseja usar fora do padrão? pois e sugerido pelo modulo e toda a comunidade a utilização deste modo, acredito que cabe sempre que vermos isso orientar as pessoas a utilização correta, assim podemos ir amadurecendo os times para que estejam no mesmo padrão de desenvolvimento com o de projetos Opensources.

**Comment by jhosefmarks** [comment]
Resolvido!!!
